### ISSUE TITLE
Refine pulldata function

### ISSUE THREAD

**Issue by chrismclarke** [stats4sd/kobo-api-app#3]
I want to give a quick tidy to the pulldata function, I gather that its purpose was to gather 'new' responses for a given form (and ideally all forms), with a couple different strategies tried including use of tags and queries.

My initial thoughts are that no, I can't see a way to query all submissions, so multiple queries for each form will be required. I would suggest simply opting to pull all data, as the sizes we are talking about are very small, and everything is server side anyway (so minimal time difference using query filter on kobo database vs custom filter on node app). 

So firstly does this sound like a sensible option for me to implement?

Secondly, you are sending a list of submission IDs to match against, does this mean we are not interested in submissions which may have been modified? Otherwise I would suggest just sending the date modified of the last submission in the database and then filtering the kobo db submissions for greater than that date (I assume the date modified field is accurate enough/kobo clever enough to avoid simultaneous upload)

Therefore would an endpoint like customFormSubmissions(dateFrom?) be of use in place? @dave-mills

**Comment by dave-mills** [comment]
Good question about modified submissions. The intention with the NRC app is that no-one will be looking directly at the Kobo server, so there won't be any data editing until it's already in their custom database.  That might not be true for other projects in the future, I guess, 

**pulling data from kobo**
Mm - completely agree that just pulling all the records from Kobo makes more sense than trying to query-filter it. Even with the numbers I'm expecting from NRC (potential for 20,000+ records to appear quite quickly across different forms), as you say - kobo -> node is still quick. node -> sql database is less quick. 

I honestly don't know the performance implications of making 20,000 postgres `insert / on duplicate id update` type requests with each kobo pull would be. Possibly fine, but I'm sure it'd be easier on the platform to filter before sending to the db (so either in here in node, or within my PMT app before sending to the db - and keeping it here in node means I can ask you to write it! 😇)

**Checking for dups**
Unfortunately, I've definitely seen multiple records from a form with the same `_submission_time` (at least from Ona, which gives a submission time field down to the nearest second), so I wouldn't trust that as a way of ensuring we get all of the new ones and no duplicates. Might be able to look at `_id` (if Kobo has that in the same way Ona does?), as I believe that's meant to be a sequential integer - but again I'm not sure I trust that to be infallibly chronological.

The `_uuid` matching is a bit painful, but I couldn't see a better way of ensuring I was only adding records to the postgres db that weren't already there.  (if you find a less painful way, let me know!)

**Comment by chrismclarke** [comment]
Ok, modifying makes sense let's not overcomplicate for now. So then we have a **choice of fields to work with**, I would suggest we opt for one that is both unique and increasing with time so that we don't have to large filter operations (apply single filter to each record as opposed to comparing against all others). I think `_id` should do the trick on that although I'd still want to first check how it is implemented on kobo (its non-sequential, so I'm guessing somehow related to time, although clearly not epoch). Alternatively there's the hex `meta/instanceID` field which again I assumed would be epoch but isn't.  

The second question is **whether this is needed at all?** I mean, are you trying to keep a working copy of all the kobo data in the postgres db? If so wouldn't it be easier to just query when needed (everything's on the same server so none of these really should take much time at all). The second question arises of when to do this? Ideally you don't want to run the query triggered by user action (such as opening the dashboard) as multiple users would be triggering the same check/write operations which would be horribly inefficient and risky if two users both did things at a vaguely similar time (initialising 20k async read/write operations on postgres). The second option would be to add a chron task to schedule this, however again I think there would be an expectation for the data to be there immediately after the user knows it has been submitted successfully.

**Comment by dave-mills** [comment]
I'd say it is needed, at least to make it easier for the various tasks we want to do with the data. Things like populating dashboards, linking into Qlik / Alteryx and writing custom queries are all much easier to do with the data sitting in postgres rather than going to kobo each time.  (at least, much easier for me and the NRC people who'll want to interact with the data, especially as it's easily joinable with various metadata like project info). 

**When** is a very good question. I currently do have the janky setup of "user clicks button" =>  `countRecords` request is sent for their forms. If that shows more records on kobo than in postgres, it then sends the `pullData` request.  (So at least it's only pulling all the data if there's definitely data on kobo that isn't on postgres. It does break if someone goes straight to kobo and deletes some records, I'm not sure if we need to protect against that sort of vandalism).

Cron could work, at least as a thing to ensure that a manually activated pull would only ever have a small handful of new records to pull? But I agree it wouldn't work as the only pull option. 

I really wish we could add a JSON REST thingy to a form that we push through the API. Then we could just push records, and use pull / count records just to double-check. (I spent ages looking for this option a while ago. Frustratingly, it appears to be in the [Ona.io API](https://api.ona.io/static/docs/restservices.html#add-a-rest-service-to-a-form), but this doesn't work for Kobo... 😐)

**Comment by chrismclarke** [comment]
There's just something about, creating an api to extend the kobo api (that already exists to  expose data in the kobo postgres database) so that it can be copied into a second postgres database so that query methods can be written on top of it, that still just doesn't quite sit right with me!

If we keep the dashboard limited to showing summary data at the form (or possibly project level) then generating headline statistics (e.g. total submission for a form/across these 5 forms etc.) should be easy and robust relying just on the 'read-data' style apis that exist or that we are extending. 

If we want to start using the data beyond this (e.g across all forms of the system) then I would suggest we create a couple seperate 'export-data' api endpoints that can just be triggered on request and used to do things like take a copy of all the data, repopulate a second database if prefferred, reshape and export. That way we don't have to worry about janky syncing methods. 

Essentially what I'm trying to suggest is that as we already have one 'truth source', it would make sense to prioritise using that when easy to do. You know the full data system much better than me so I'll of course leave to your best judgement, but just something to consider.

**Comment by dave-mills** [comment]
I think I get what you mean - if we had full/deep knowledge of Kobo's setup and future development we could just be interacting directly with the databases behind Kobo. Copying data from platform to platform does kinda seem wasteful, but I think there is a lot of benefit to being able to get the data into a good database system that we can access / query directly.

ODK Aggregate and related tools like Kobo weren't written with proper data querying / manipulation in mind, and the querying tools in any good database system (Couch, firebase/store, sql) are much more powerful than what we could create with this app. 

In the specific case of NRC, I know that the other tools they want to use (Qlik, etc) have links to easily use sql databases (ODBC connections or similar), but would struggle to play nice linking with this app or Kobo. 

I think I would prefer to leave the data querying to the database tools, and focus here on checking that we can get everything out of Kobo cleanly without duplicates. If you think the best way to do that is to just pull all the data each time, and let the app on the other end do the duplicate checking, fair enough.

**Comment by dave-mills** [comment]
Maybe the `customFormSubmissions(dateFrom?)` idea would be of use? Where if the external db has records from the 24th May and earlier, it sends a request to get all records starting on the 24th May. Then you're guaranteed some duplicates, but only among the 24th May records, so it'd be much easier / quicker to check through those records than all records since the beginning of time? (And the checking could be done by the requesting app when it gets the records back).

Just a thought.

**Comment by chrismclarke** [comment]
> if we had full/deep knowledge of Kobo's setup and future development we could just be interacting directly with the databases behind Kobo

I think this is definitely worth revisiting at some point. We don't need to know future development as anything we make is based on the current database structures (which also are highly unlikely to change in fundamentally breaking ways... the approach taken so far has been to tack on another database the moment an existing one doesn't do what is needed. It's a huge ecosystem not worth breaking). In the `settings.py` file of kpi-master it provides the ports and user/pass setup for both the postgres and mongo dbs which run behind kobo (and are kept in sync). 

Agreed that we shouldn't be querying via web apis, I still stand by using the existing `/data`  and `/dataview` endpoints for simple summative data, but will also work on some options for pulling/syncing/exporting data more generally. **Although any reason to not just use the submission _id number?** (as an increasing, although non-sequential, id, instead of dates as I mentioned in an above comment?).

**Comment by dave-mills** [comment]
I guess not, assuming that the submission _id number is generated by the kobo server, so there’s no chance of accidentally missing one out.

Fair - you’ve broken through my not-totally-logical distrust of anything other than the _uuid. :-D Go for the _id.

Agreed that the kobo db stuff is worth investigating more at some point, when we both have more time to experiment.

On 26 May 2018, at 16:39, Chris Clarke <notifications@github.com<mailto:notifications@github.com>> wrote:


if we had full/deep knowledge of Kobo's setup and future development we could just be interacting directly with the databases behind Kobo

I think this is definitely worth revisiting at some point. We don't need to know future development as anything we make is based on the current database structures (which also are highly unlikely to change in fundamentally breaking ways... the approach taken so far has been to tack on another database the moment an existing one doesn't do what is needed. It's a huge ecosystem not worth breaking). In the settings.py file of kpi-master it provides the ports and user/pass setup for both the postgres and mongo dbs which run behind kobo (and are kept in sync).

Agreed that we shouldn't be querying via web apis, I still stand by using the existing /data and /dataview endpoints for simple summative data, but will also work on some options for pulling/syncing/exporting data more generally. Although any reason to not just use the submission _id number? (as an increasing, although non-sequential, id, instead of dates as I mentioned in an above comment?).

**Comment by chrismclarke** [comment]
the problem with uuid is that there's no way of ordering it. Xform specs give an 

>  RFC 4122 version 4 compliant UUID

(https://opendatakit.github.io/xforms-spec/#fn:uuid)

This means that it is intended to create an entirely random identifier ([link](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random))).

Now that I've taken another look at the **_id** I'm 99% sure that like the project (and form?) ids, this is simply **a counter given across all forms within the server**, populated either during core sql or mongo write operations. So actually pretty ideal for querying 'latest' data.

**Comment by chrismclarke** [comment]
implemented with fe49c0fe34d429806e401065253096aaec502cef
The endpoint is 'customPullData' and takes formID and latestSubmissionNumber values (full code in koboExportApi, and see corresponding test).  Response includes countTotal and countNew fields as well as 'data' which has the actual new records.
Moving to review
